### ISSUE TITLE
focus countdown works fine. break never starts.

### ISSUE THREAD

**Issue by taw00** [liyunze-coding/streamodoro#1]
Installed it.

I turned off the discord notification thingy ("false" for that setting). I stitched it up into OBS (Linux) and then tested with …

```
!setpomos 3
!timer 2m focus
!timer 1m break
```

It counts down for two minutes and then just … stops. Not sure what is up with that. Also if I do `!restart` in the middle of a countdown, it stops and never recovers.

I don't know if this is user error or something with the software. Does it log anywhere?

Cheers.

**Comment by liyunze-coding** [comment]
@taw00 the command `!timer 1m break` should be typed in chat after the focus time is over. I will specify that in the instructions soon. Thank you.

**Comment by liyunze-coding** [comment]
If you prefer a timer that starts automatically, I recommend MohFocus' timer that can be found [here](https://github.com/mohamed-tayeh/Minimal-Pomo-Timer)

**Comment by taw00** [comment]
This timer is deprecated and recommends MohFocus' timer. See README.
